import { listBookingDeliveryRecordsWithRevision } from "@/lib/booking-delivery";
import { pushLineText } from "@/lib/line";
import { appendRddActivity } from "@/lib/rdd-activity";
import { bangkokDateKey } from "@/lib/rdd-phase2";
import { RDD_PREP_LABELS, derivePrepReminder, prepStatusForRecord } from "@/lib/rdd-phase3c";
import { getRddLineSettings } from "@/lib/rdd-line-settings";
import { RddWorkspaceWriteError, updateRddWorkspaceRecord } from "@/lib/rdd-workspace-write";
import type { RddWorkspaceChanges, RddWorkspaceEditableField } from "@/lib/rdd-workspace-fields";
import type { BookingDeliveryRecord } from "@/lib/types";
import { readJsonStore, writeJsonStore } from "@/lib/json-store";
type TaskKey="wash"|"sticker"|"oil"|"battery"|"tax"|"insurance"|"garage"; type TaskState="pending"|"done"|"blocked"; type PendingChoice={groupId:string;userId:string;caseIds:string[];createdAt:string;selectedCaseId?:string};
const taskMatchers:Array<[TaskKey,RegExp]>=[["wash",/(?:ล้างรถ|ล้าง|สปา)/i],["sticker",/(?:ลอกสติ๊กเกอร์|ลอกสติกเกอร์|สติ๊กเกอร์|สติกเกอร์|ลอกลาย)/i],["oil",/(?:น้ำมันเครื่อง|เปลี่ยนน้ำมัน)/i],["battery",/(?:แบตเตอรี่|แบต)/i],["tax",/(?:ต่อภาษี|ภาษี)/i],["insurance",/(?:ประกันภัย|ประกัน)/i],["garage",/(?:รถกลับ|ส่งอู่|เข้าอู่|อู่)/i]];
const taskLabels:Record<TaskKey,string>={wash:"ล้างรถ",sticker:"ลอกสติ๊กเกอร์",oil:"น้ำมันเครื่อง",battery:"แบตเตอรี่",tax:"ภาษี",insurance:"ประกัน",garage:"อู่ / รถกลับ"},webhookStoreFile="rdd-line-webhook-events.json",choiceStoreFile="rdd-line-case-choices.json";
export async function wasRddLineWebhookProcessed(eventId:string){if(!eventId)return false;const store=await readJsonStore<{ids?:string[]}>(webhookStoreFile,{ids:[]});return Array.isArray(store.ids)&&store.ids.includes(eventId)}
export async function rememberRddLineWebhook(eventId:string){if(!eventId)return;const store=await readJsonStore<{ids?:string[]}>(webhookStoreFile,{ids:[]}),ids=Array.isArray(store.ids)?store.ids:[];if(!ids.includes(eventId))await writeJsonStore(webhookStoreFile,{ids:[eventId,...ids].slice(0,1000)})}
function normalizePlate(v:unknown){return String(v||"").normalize("NFKC").toUpperCase().replace(/[^0-9A-Zก-๙]/g,"")} function normalizeText(v:unknown){return String(v||"").normalize("NFKC").toLowerCase().replace(/\s+/g,"").trim()} function statusSymbol(v:unknown){if(v==="blocked")return"❌";return["completed","changed","replaced","valid","with_us","customer_self","no_change","good","no_sticker"].includes(String(v))?"✅":""} function prepLine(l:string,v:string|undefined,labels:Record<string,string>){const s=statusSymbol(v);return`${l}: ${labels[v||""]||"ยังไม่ระบุ"}${s?` ${s}`:""}`}
export function formatRddLineCase(record:BookingDeliveryRecord){const prep=prepStatusForRecord(record),has=Boolean(record.garageName||record.garageSentAt||record.garageOutDate||record.garageExpectedReturnDate||record.garageReturnDate||record.garageReturned);const garage=record.garageRequired===false&&!has?"ไม่ส่งอู่":record.garageRequired===true||has?(record.garageReturned?"รถกลับแล้ว ✅":`ส่งอู่ / รถยังไม่กลับ${record.garageSentAt||record.garageOutDate?` · ไปอู่ ${record.garageSentAt||record.garageOutDate}`:""}${record.garageExpectedReturnDate||record.garageReturnDate?` · กลับ ${record.garageExpectedReturnDate||record.garageReturnDate}`:""}`):"ยังไม่ระบุ";return[`ติดตาม ${record.plate||"-"} · ${record.customerName||"-"}`,`สถานะ: ${record.workflowStatus||record.status||"ไม่ระบุ"}`,`ส่งมอบ: ${[record.deliveryDate,record.deliveryTime,record.deliveryLocation].filter(Boolean).join(" · ")||"ยังไม่ระบุ"}`,`อู่: ${garage}`,prepLine("ล้างรถ",prep.washStatus,RDD_PREP_LABELS.washStatus),prepLine("ลอกสติ๊กเกอร์",prep.stickerStatus,RDD_PREP_LABELS.stickerStatus),prepLine("น้ำมันเครื่อง",prep.oilStatus,RDD_PREP_LABELS.oilStatus),prepLine("แบตเตอรี่",prep.batteryStatus,RDD_PREP_LABELS.batteryStatus),prepLine("ภาษี",prep.taxStatus,RDD_PREP_LABELS.taxStatus),prepLine("ประกัน",prep.insuranceStatus,RDD_PREP_LABELS.insuranceStatus),record.financeCaseNote?`หมายเหตุ: ${record.financeCaseNote}`:""].filter(Boolean).join("\n")}
function findRecords(records:BookingDeliveryRecord[],q:string){const parts=String(q||"").trim().split(/\s+/).filter(Boolean);if(!parts.length)return[];let plate=parts[0];if(parts.length>=2&&/[ก-๙A-Z]/i.test(parts[0])&&/\d/.test(parts[1]))plate=`${parts[0]}${parts[1]}`;let m=(()=>{const x=normalizePlate(plate);if(!x)return[];const e=records.filter(r=>normalizePlate(r.plate)===x);return e.length?e:records.filter(r=>normalizePlate(r.plate).includes(x))})();const consumed=plate===parts[0]?1:2,n=normalizeText(parts.slice(consumed).join(" "));if(n)m=m.filter(r=>normalizeText(r.customerName).includes(n));return m}
function choiceKey(g:string,u?:string){return`${g}:${u||"group"}`} async function saveChoices(g:string,u:string|undefined,m:BookingDeliveryRecord[]){const s=await readJsonStore<Record<string,PendingChoice>>(choiceStoreFile,{}),k=choiceKey(g,u);s[k]={groupId:g,userId:u||"",caseIds:m.slice(0,8).map(r=>String(r.id)),createdAt:new Date().toISOString()};await writeJsonStore(choiceStoreFile,s)} async function takeChoice(g:string,u:string|undefined,n:number,records:BookingDeliveryRecord[]){const s=await readJsonStore<Record<string,PendingChoice>>(choiceStoreFile,{}),k=choiceKey(g,u),p=s[k];if(!p||Date.now()-Date.parse(p.createdAt)>600000){if(p){delete s[k];await writeJsonStore(choiceStoreFile,s)}return null}const id=p.caseIds[n-1];if(!id)return null;const chosen=records.find(r=>String(r.id)===id)||null;if(!chosen)return null;s[k]={...p,selectedCaseId:id,caseIds:[id],createdAt:new Date().toISOString()};await writeJsonStore(choiceStoreFile,s);return chosen}
export async function getSelectedRddLineCaseId(g:string,u?:string){const s=await readJsonStore<Record<string,PendingChoice>>(choiceStoreFile,{}),p=s[choiceKey(g,u)];return p?.selectedCaseId&&Date.now()-Date.parse(p.createdAt)<=600000?p.selectedCaseId:""}
function duplicatePrompt(m:BookingDeliveryRecord[]){return`พบ ${m.length} เคส เลือกเคสที่ต้องการ:\n${m.slice(0,8).map((r,i)=>`${i+1}. ${r.plate} · ${r.customerName||"-"} · ${r.workflowStatus||r.status||"ไม่ระบุ"}`).join("\n")}\n\nตอบเฉพาะเลข 1-${Math.min(m.length,8)} ภายใน 10 นาที\nหรือพิมพ์: ติดตาม 2737 ชื่อลูกค้า`} function parseTaskState(t:string):TaskState{return t.includes("❌")?"blocked":t.includes("✅")?"done":"pending"}
function taskChanges(task:TaskKey,state:TaskState,t=""):RddWorkspaceChanges{if(task==="garage"){if(state==="blocked")throw new Error("งานอู่ยังไม่รองรับ ❌ กรุณาใส่เหตุผลไว้ในหมายเหตุของเคส");const d=t.match(/\b(20\d{2}-\d{2}-\d{2})\b/)?.[1];if(state==="done")return{garageRequired:true,garageReturned:true};if(/ส่งอู่|เข้าอู่/.test(t)&&d)return{garageRequired:true,garageSentAt:d,garageReturned:false};if(/รถกลับ/.test(t)&&d)return{garageRequired:true,garageExpectedReturnDate:d,garageReturned:false};return{garageRequired:true,garageReturned:false}}const vals:Record<Exclude<TaskKey,"garage">,Record<TaskState,string>>={wash:{pending:"ordered_waiting",done:"completed",blocked:"blocked"},sticker:{pending:"ordered_waiting",done:"completed",blocked:"blocked"},oil:{pending:"change_waiting",done:"changed",blocked:"blocked"},battery:{pending:"ordered_waiting",done:"replaced",blocked:"blocked"},tax:{pending:"not_checked",done:"valid",blocked:"blocked"},insurance:{pending:"not_discussed",done:"with_us",blocked:"blocked"}},fs:Record<Exclude<TaskKey,"garage">,keyof RddWorkspaceChanges>={wash:"washStatus",sticker:"stickerStatus",oil:"oilStatus",battery:"batteryStatus",tax:"taxStatus",insurance:"insuranceStatus"};return{[fs[task]]:vals[task][state]} as RddWorkspaceChanges}
export function isRddLineTrackerCommand(t:string){return/^\s*(?:(?:ติดตาม|งาน)\s+|[1-8]\s*$)/i.test(String(t||""))} function parseUpdateCommand(t:string){const r=t.replace(/^งาน\s+/i,""),m=taskMatchers.map(([task,pattern])=>({task,match:pattern.exec(r)})).filter((x):x is{task:TaskKey;match:RegExpExecArray}=>Boolean(x.match)).sort((a,b)=>a.match.index-b.match.index),f=m[0];return!f||f.match.index===0?null:{plate:r.slice(0,f.match.index).trim(),task:f.task,taskText:r.slice(f.match.index).trim()}}
export async function handleRddLineTrackerMessage(input:{text:string;sourceGroupId:string;sourceUserId?:string}){const text=String(input.text||"").trim();if(!isRddLineTrackerCommand(text))return null;const settings=await getRddLineSettings();if(!settings.enabled||!settings.groupId||settings.groupId!==input.sourceGroupId)return null;const snapshot=await listBookingDeliveryRecordsWithRevision();if(/^[1-8]$/.test(text)){const c=await takeChoice(input.sourceGroupId,input.sourceUserId,Number(text),snapshot.records);return c?formatRddLineCase(c):null}const q=text.match(/^ติดตาม\s+(.+)$/i);if(q){const m=findRecords(snapshot.records,q[1]);if(!m.length)return"ไม่พบรถตามทะเบียน/ชื่อลูกค้าที่ค้นหา";if(m.length>1){await saveChoices(input.sourceGroupId,input.sourceUserId,m);return duplicatePrompt(m)}return formatRddLineCase(m[0])}const u=parseUpdateCommand(text);if(!u)return`รูปแบบคำสั่ง: งาน 3405 ล้างรถ ✅\nรองรับ: ${Object.values(taskLabels).join(", ")}`;const task=u.task,state=parseTaskState(u.taskText);for(let a=0;a<3;a++){const cur=a===0?snapshot:await listBookingDeliveryRecordsWithRevision(),m=findRecords(cur.records,u.plate);if(!m.length)return"ไม่พบรถตามทะเบียน/ชื่อลูกค้าที่ค้นหา";if(m.length>1){await saveChoices(input.sourceGroupId,input.sourceUserId,m);return`${duplicatePrompt(m)}\n\nเพื่ออัปเดตทันที ใช้: งาน 2737 ชื่อลูกค้า ${u.taskText}`}try{const changes=taskChanges(task,state,u.taskText),result=await updateRddWorkspaceRecord({id:m[0].id,expectedRevision:cur.revision,changes,actor:{id:`line:${input.sourceUserId||input.sourceGroupId}`,role:"sales"}});await appendRddActivity(null,{action:"booking_delivery_updated",targetType:"booking_delivery",targetId:result.record.id,source:"line",before:result.before,after:result.after,metadata:{changedFields:result.changedFields,lineUserId:input.sourceUserId||"",lineGroupId:input.sourceGroupId}}).catch(()=>undefined);const s=state==="done"?"✅":state==="blocked"?"❌":"";return`อัปเดต ${result.record.plate} · ${result.record.customerName||"-"} แล้ว\n${taskLabels[task]}: ${state==="done"?"เสร็จ":state==="blocked"?"ทำไม่ได้":"งานค้าง"}${s?` ${s}`:""}`}catch(e){if(e instanceof RddWorkspaceWriteError&&e.status===409&&a<2)continue;if(e instanceof RddWorkspaceWriteError&&e.message==="ไม่มีข้อมูลที่เปลี่ยนแปลง")return`${m[0].plate} · ${m[0].customerName||"-"} · ${taskLabels[task]} เป็นสถานะนี้อยู่แล้ว`;throw e}}return"ข้อมูลมีการเปลี่ยนพร้อมกัน กรุณาลองใหม่"}
export async function notifyRddLineWebUpdate(record:BookingDeliveryRecord,_changedFields:RddWorkspaceEditableField[],_after:Record<string,unknown>,actorName:string){const s=await getRddLineSettings();if(!s.enabled||!s.groupId)return{sent:false,reason:"disabled" as const};const canonical=formatRddLineCase(record);await pushLineText(s.groupId,[canonical,"",actorName?`อัปเดตจาก BIG CAR RDD · ${actorName}`:"อัปเดตจาก BIG CAR RDD"].join("\n"));return{sent:true}}
export async function sendRddLinePendingReminder(){const s=await getRddLineSettings();if(!s.enabled||!s.reminderEnabled||!s.groupId)return{sent:false,count:0};const{records}=await listBookingDeliveryRecordsWithRevision(),today=bangkokDateKey(),pending=records.map(record=>({record,reminder:derivePrepReminder(record,today)})).filter(x=>x.reminder.eligible&&x.reminder.pendingPrepCount>0).sort((a,b)=>b.reminder.urgentPrepCount-a.reminder.urgentPrepCount||b.reminder.pendingPrepCount-a.reminder.pendingPrepCount);if(!pending.length){await pushLineText(s.groupId,`สรุปงานค้าง ${today}\nไม่มีงานเตรียมรถค้าง ✅`);return{sent:true,count:0}}const rows=pending.slice(0,40).map(({record,reminder})=>`• ${record.plate} · ${reminder.reminderItems.map(i=>i.label).join(", ")}${reminder.urgentPrepCount?" ⚠️":""}`),suffix=pending.length>rows.length?`\nและอีก ${pending.length-rows.length} คัน`:"";await pushLineText(s.groupId,`สรุปงานค้าง ${today} · ${pending.length} คัน\n${rows.join("\n")}${suffix}\n\nพิมพ์: ติดตาม <ทะเบียน>`);return{sent:true,count:pending.length}}
