'use client';
import { useEffect,useState } from 'react';
type Field='washStatus'|'stickerStatus'|'oilStatus'|'batteryStatus'|'taxStatus'|'insuranceStatus';
type CustomTask={id:string;title:string;done:boolean;createdAt?:string;updatedAt?:string};
type Task={field:Field;label:string;options:{value:string;label:string}[]};
const tasks:Task[]=[
{field:'washStatus',label:'ล้างรถ',options:[{value:'not_ordered',label:'ยังไม่สั่ง'},{value:'ordered_waiting',label:'รอล้าง'},{value:'completed',label:'ล้างแล้ว ✓'}]},
{field:'stickerStatus',label:'ลอกสติ๊กเกอร์',options:[{value:'not_checked',label:'ยังไม่ตรวจ'},{value:'no_sticker',label:'ไม่มีสติ๊กเกอร์'},{value:'ordered_waiting',label:'รอลอก'},{value:'completed',label:'ลอกแล้ว ✓'}]},
{field:'oilStatus',label:'น้ำมันเครื่อง',options:[{value:'no_change',label:'ไม่เปลี่ยน'},{value:'change_waiting',label:'รอเปลี่ยน'},{value:'changed',label:'เปลี่ยนแล้ว ✓'}]},
{field:'batteryStatus',label:'แบตเตอรี่',options:[{value:'not_checked',label:'ยังไม่ตรวจ'},{value:'good',label:'ปกติ ✓'},{value:'ordered_waiting',label:'รอเปลี่ยน'},{value:'replaced',label:'เปลี่ยนแล้ว ✓'}]},
{field:'taxStatus',label:'ภาษี',options:[{value:'not_checked',label:'ยังไม่ตรวจ'},{value:'valid',label:'ไม่ขาด ✓'},{value:'renewal_ordered',label:'สั่งต่อแล้ว'}]},
{field:'insuranceStatus',label:'ประกัน',options:[{value:'not_discussed',label:'ยังไม่คุย'},{value:'with_us',label:'ทำกับเรา ✓'},{value:'customer_self',label:'ลูกค้าทำเอง'}]}];
export default function Page(){
 const [query,setQuery]=useState<string|null>(null); const [data,setData]=useState<any>(null); const [base,setBase]=useState<Record<string,string>>({}); const [values,setValues]=useState<Record<string,string>>({}); const [baseDates,setBaseDates]=useState({deliveryDate:'',garageSentAt:'',garageExpectedReturnDate:''}); const [dates,setDates]=useState({deliveryDate:'',garageSentAt:'',garageExpectedReturnDate:''}); const [custom,setCustom]=useState<CustomTask[]>([]); const [baseCustom,setBaseCustom]=useState<CustomTask[]>([]); const [title,setTitle]=useState(''); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{setQuery(window.location.search.replace(/^\?/,''))},[]);
 useEffect(()=>{if(query===null)return;if(!query){setMessage('ลิงก์เคสไม่ครบ กรุณาเปิดจาก LINE ใหม่');return}fetch('/api/line/task-panel?'+query).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||'โหลดไม่สำเร็จ');return j}).then(j=>{setData(j);setBase(j.statuses);setValues(j.statuses);const d=j.dates||{deliveryDate:'',garageSentAt:'',garageExpectedReturnDate:''};setBaseDates(d);setDates(d);setCustom(j.customTasks||[]);setBaseCustom(j.customTasks||[])}).catch(e=>setMessage(e.message))},[query]);
 const dateChanged=(dates.deliveryDate!==baseDates.deliveryDate?1:0)+(dates.garageSentAt!==baseDates.garageSentAt?1:0)+(dates.garageExpectedReturnDate!==baseDates.garageExpectedReturnDate?1:0); const changed=tasks.filter(t=>values[t.field]!==base[t.field]).length+dateChanged+(JSON.stringify(custom.map(x=>[x.id,x.title,x.done]))!==JSON.stringify(baseCustom.map(x=>[x.id,x.title,x.done]))?1:0);
 const add=()=>{const v=title.trim();if(!v)return;setCustom(x=>[...x,{id:`new-${Date.now()}`,title:v,done:false}]);setTitle('')};
 const save=async()=>{if(!data||!changed)return;setBusy(true);setMessage('');const changes:any={};tasks.forEach(t=>{if(values[t.field]!==base[t.field])changes[t.field]=values[t.field]});(['deliveryDate','garageSentAt','garageExpectedReturnDate'] as const).forEach(f=>{if(dates[f]!==baseDates[f])changes[f]=dates[f]});try{const r=await fetch('/api/line/task-panel',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:data.id,expectedRevision:data.revision,changes,customTasks:custom})});const j=await r.json();if(!r.ok)throw new Error(j.error||'บันทึกไม่สำเร็จ');setData((d:any)=>({...d,revision:j.revision}));setBase(j.statuses);setValues(j.statuses);const nd=j.dates||dates;setBaseDates(nd);setDates(nd);setCustom(j.customTasks);setBaseCustom(j.customTasks);setMessage(j.lineSent?'บันทึกแล้ว และอัปเดตสรุปใน LINE เรียบร้อย ✓':'บันทึกแล้ว แต่ส่งข้อความ LINE ไม่สำเร็จ');}catch(e:any){setMessage(e.message)}finally{setBusy(false)}};
 if(!data)return <main style={{padding:24,fontFamily:'system-ui'}}>{message||'กำลังโหลดเคส...'}</main>;
 const inputStyle={display:'block',width:'100%',boxSizing:'border-box' as const,marginTop:6,border:'1px solid #d0d5dd',borderRadius:12,padding:11,fontSize:16};
 return <main style={{minHeight:'100vh',background:'#f5f7f9',padding:'16px 14px 120px',fontFamily:'system-ui,-apple-system,sans-serif',color:'#17212b'}}><section style={{maxWidth:620,margin:'0 auto'}}><div style={{fontSize:13,color:'#667085'}}>BIG CAR RDD · อัปเดตงานรถ</div><h1 style={{fontSize:28,margin:'6px 0'}}>{data.plate}</h1><div style={{fontSize:17,marginBottom:18}}>{data.customerName}</div>
 <div style={{background:'#fff',borderRadius:16,padding:14,marginBottom:12,boxShadow:'0 1px 4px rgba(0,0,0,.06)'}}><b style={{fontSize:18}}>🚚 วันส่งมอบ</b><label style={{display:'block',fontSize:14,fontWeight:700,marginTop:12}}>วันส่งมอบ<input type='date' value={dates.deliveryDate} onChange={e=>setDates(d=>({...d,deliveryDate:e.target.value}))} style={inputStyle}/></label></div>
 <div style={{background:'#fff',borderRadius:16,padding:14,marginBottom:12,boxShadow:'0 1px 4px rgba(0,0,0,.06)'}}><b style={{fontSize:18}}>🔧 วันที่เข้า-กลับอู่</b><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,marginTop:12}}><label style={{fontSize:14,fontWeight:700}}>วันไปอู่<input type='date' value={dates.garageSentAt} onChange={e=>setDates(d=>({...d,garageSentAt:e.target.value}))} style={inputStyle}/></label><label style={{fontSize:14,fontWeight:700}}>วันกลับอู่<input type='date' value={dates.garageExpectedReturnDate} onChange={e=>setDates(d=>({...d,garageExpectedReturnDate:e.target.value}))} style={inputStyle}/></label></div></div>
 {tasks.map(t=><div key={t.field} style={{background:'#fff',borderRadius:16,padding:14,marginBottom:10,boxShadow:'0 1px 4px rgba(0,0,0,.06)'}}><b style={{fontSize:17}}>{t.label}</b><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:10}}>{t.options.map(o=>{const active=values[t.field]===o.value;return <button key={o.value} onClick={()=>setValues(v=>({...v,[t.field]:o.value}))} style={{border:active?'2px solid #06c755':'1px solid #d0d5dd',background:active?'#e9fbea':'#fff',borderRadius:12,padding:'10px 12px',fontSize:15,fontWeight:active?700:500}}>{o.label}</button>})}</div></div>)}
 <div style={{background:'#fff',borderRadius:16,padding:14,marginTop:14}}><b style={{fontSize:18}}>➕ งานอื่น</b><div style={{display:'flex',gap:8,marginTop:12}}><input value={title} onChange={e=>setTitle(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder='เช่น เช็กแอร์, เก็บสีประตู' style={{flex:1,minWidth:0,border:'1px solid #d0d5dd',borderRadius:12,padding:12,fontSize:16}}/><button onClick={add} style={{border:0,borderRadius:12,padding:'0 16px',background:'#17212b',color:'#fff',fontWeight:700}}>เพิ่ม</button></div>
 {custom.map((x,i)=><div key={x.id} style={{borderTop:'1px solid #eee',padding:'12px 0 2px',marginTop:10}}><div style={{fontWeight:700,marginBottom:8}}>{x.title}</div><div style={{display:'flex',gap:8}}><button onClick={()=>setCustom(a=>a.map((v,n)=>n===i?{...v,done:false}:v))} style={{border:!x.done?'2px solid #f59e0b':'1px solid #ddd',background:!x.done?'#fff7e6':'#fff',borderRadius:10,padding:'9px 11px'}}>⏳ ยังไม่เรียบร้อย</button><button onClick={()=>setCustom(a=>a.map((v,n)=>n===i?{...v,done:true}:v))} style={{border:x.done?'2px solid #06c755':'1px solid #ddd',background:x.done?'#e9fbea':'#fff',borderRadius:10,padding:'9px 11px'}}>✅ เรียบร้อย</button><button onClick={()=>setCustom(a=>a.filter((_,n)=>n!==i))} style={{marginLeft:'auto',border:0,background:'transparent'}}>ลบ</button></div></div>)}</div>
 {message&&<div style={{marginTop:12,padding:12,borderRadius:12,background:message.includes('ไม่สำเร็จ')?'#fff1f0':'#e9fbea',fontWeight:700,textAlign:'center'}}>{message}</div>}</section><div style={{position:'fixed',left:0,right:0,bottom:0,background:'#fff',padding:'12px 14px calc(12px + env(safe-area-inset-bottom))',boxShadow:'0 -2px 10px rgba(0,0,0,.08)'}}><button disabled={!changed||busy} onClick={save} style={{display:'block',width:'100%',maxWidth:620,margin:'0 auto',border:0,borderRadius:14,padding:14,fontSize:17,fontWeight:800,background:changed&&!busy?'#06c755':'#d0d5dd',color:'#fff'}}>{busy?'กำลังบันทึก...':`✓ บันทึกการเปลี่ยนแปลง${changed?` (${changed})`:''}`}</button></div></main>;
}